#!/bin/bash
# OverSeek Setup Script
# Generates stack.env with secure defaults — run once before docker compose up

set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No color
BOLD='\033[1m'

echo ""
echo -e "${BOLD}${CYAN}  OverSeek — Self-Hosted Setup${NC}"
echo -e "  ─────────────────────────────────"
echo ""

# ── Bail if stack.env already exists ──────────────────────────────────────────
if [ -f "stack.env" ]; then
    echo -e "${YELLOW}⚠  stack.env already exists.${NC}"
    echo "   To reconfigure, delete or rename it first."
    echo ""
    exit 0
fi

# ── Parse CLI args ────────────────────────────────────────────────────────────
DOMAIN=""
APP_NAME="OverSeek"
for arg in "$@"; do
    case $arg in
        --domain=*) DOMAIN="${arg#*=}" ;;
        --name=*)   APP_NAME="${arg#*=}" ;;
    esac
done

# ── Interactive prompts (if not passed via CLI) ───────────────────────────────
if [ -z "$DOMAIN" ]; then
    echo -e "${BOLD}Where will the OverSeek dashboard be hosted?${NC}"
    echo "  (This is NOT your WooCommerce store — it's where you access the dashboard)"
    echo "  Examples: localhost, overseek.example.com"
    echo ""
    read -rp "  Domain [localhost]: " DOMAIN
    DOMAIN="${DOMAIN:-localhost}"
    echo ""
fi

# ── Sanitize domain input ─────────────────────────────────────────────────────
# Strip protocol if user entered a full URL (e.g., https://myapp.example.com)
# Note: two seds instead of \? because \? is GNU-only (breaks on macOS BSD sed)
DOMAIN=$(echo "$DOMAIN" | sed 's|^https://||' | sed 's|^http://||')
# Strip trailing path, slashes, and whitespace
DOMAIN=$(echo "$DOMAIN" | sed 's|/.*$||' | tr -d '[:space:]')

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}✗  Domain cannot be empty.${NC}"
    exit 1
fi

# ── Derive URLs ───────────────────────────────────────────────────────────────
if [ "$DOMAIN" = "localhost" ] || [ "$DOMAIN" = "127.0.0.1" ]; then
    APP_URL="http://localhost:5173"
    API_URL="http://localhost:3000"
else
    APP_URL="https://${DOMAIN}"
    API_URL="https://api.${DOMAIN}"
fi

# ── Generate secrets ──────────────────────────────────────────────────────────
generate_secret() {
    local len="$1"
    local result=""

    if command -v openssl &> /dev/null; then
        result=$(openssl rand -hex "$len" 2>/dev/null)
    fi

    # Fallback: /dev/urandom + od (POSIX, always available on Linux/macOS)
    # xxd is NOT universal (requires vim-common), so we avoid it
    if [ -z "$result" ] && [ -r /dev/urandom ]; then
        result=$(od -An -tx1 -N"$len" /dev/urandom | tr -d ' \n' | head -c $(( len * 2 )))
    fi

    if [ -z "$result" ]; then
        echo -e "${RED}✗  Failed to generate secrets. Install openssl or ensure /dev/urandom is readable.${NC}" >&2
        exit 1
    fi

    echo "$result"
}

PG_PASS=$(generate_secret 24)
JWT_SECRET=$(generate_secret 32)
ENCRYPTION_KEY=$(generate_secret 32)

# Sanity check — never write empty secrets
if [ -z "$PG_PASS" ] || [ -z "$JWT_SECRET" ] || [ -z "$ENCRYPTION_KEY" ]; then
    echo -e "${RED}✗  Secret generation produced empty values. Cannot continue.${NC}"
    exit 1
fi

# ── Write stack.env ───────────────────────────────────────────────────────────
# Restrict permissions — stack.env contains secrets
touch stack.env
chmod 600 stack.env

cat > stack.env << EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# For advanced options see stack.env.example

# Secrets (auto-generated — do NOT share)
POSTGRES_PASSWORD=${PG_PASS}
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Deployment
APP_NAME=${APP_NAME}
APP_URL=${APP_URL}
API_URL=${API_URL}
CONTACT_EMAIL=notifications@${DOMAIN}
EOF

# ── Summary ───────────────────────────────────────────────────────────────────
echo -e "${GREEN}✔  stack.env created successfully${NC}"
echo ""
echo -e "  ${BOLD}App URL:${NC}  ${APP_URL}"
echo -e "  ${BOLD}API URL:${NC}  ${API_URL}"
echo -e "  ${BOLD}App Name:${NC} ${APP_NAME}"
echo ""
echo -e "  Secrets have been auto-generated."
echo -e "  ${YELLOW}Keep stack.env safe — it contains your database password and encryption keys.${NC}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  docker compose up -d"
echo "  # Wait ~2-3 minutes for first-time build, then open ${APP_URL}"
echo ""
