export const ROUTE_PATHS = {
    home: '/',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    privacyPolicy: '/privacy-policy',
    dataDeletion: '/data-deletion',
    termsOfService: '/terms-of-service',
    setup: '/setup',
    dashboard: '/dashboard',
    orders: '/orders',
    abandonedCarts: '/abandoned-carts',
    inventory: '/inventory',
    supplyChain: '/inventory/supply-chain',
    inventoryBomSync: '/inventory/bom-sync',
    inventoryForecasts: '/inventory/forecasts',
    customers: '/customers',
    customerSegments: '/customers/segments',
    marketing: '/marketing',
    ads: '/ads',
    capiHealth: '/conversions/health',
    seo: '/seo',
    seoContent: '/seo/content',
    feeds: '/feeds',
    aiManager: '/ai-manager',
    broadcasts: '/broadcasts',
    emails: '/emails',
    emailLists: '/emails/lists',
    emailSettings: '/emails/settings',
    emailLogs: '/emails/logs',
    blockedContacts: '/emails/blocked-contacts',
    flows: '/flows',
    inbox: '/inbox',
    live: '/live',
    analytics: '/analytics',
    analyticsRevenue: '/analytics/revenue',
    analyticsAttribution: '/analytics/attribution',
    analyticsCohorts: '/analytics/cohorts',
    analyticsClv: '/analytics/clv',
    reviews: '/reviews',
    help: '/help',
    reports: '/reports',
    reportsGoldPriceMargin: '/reports/gold-price-margin',
    team: '/team',
    wizard: '/wizard',
    settings: '/settings',
    profile: '/profile',
    invoicesDesign: '/invoices/design',
    policies: '/policies',
    crawlers: '/crawlers',
    admin: '/admin',
    adminAccounts: '/admin/accounts',
    adminLogs: '/admin/logs',
    adminBroadcast: '/admin/broadcast',
    adminCredentials: '/admin/credentials',
    adminAiPrompts: '/admin/ai-prompts',
    adminSettings: '/admin/settings',
    adminDiagnostics: '/admin/diagnostics',
    adminBackups: '/admin/backups',
    mobileDashboard: '/m/dashboard',
    mobileOrders: '/m/orders',
    mobileInbox: '/m/inbox',
    mobileAnalytics: '/m/analytics',
    mobileInventory: '/m/inventory',
    mobileMore: '/m/more',
    mobileProfile: '/m/profile',
    mobileSettings: '/m/settings',
    mobileCustomers: '/m/customers',
    mobileNotifications: '/m/notifications',
    mobileLiveVisitors: '/m/live-visitors',
    mobileRoot: '/m',
    wildcard: '*',
} as const;

export const ROUTE_PATTERNS = {
    orderDetails: `${ROUTE_PATHS.orders}/:id`,
    productDetails: '/inventory/product/:id',
    purchaseOrderNew: '/inventory/purchase-orders/new',
    purchaseOrderEdit: '/inventory/purchase-orders/:id',
    customerDetails: `${ROUTE_PATHS.customers}/:id`,
    helpArticle: '/help/article/:slug',
    invoiceDesignerById: `${ROUTE_PATHS.invoicesDesign}/:id`,
    mobileOrderDetails: `${ROUTE_PATHS.mobileOrders}/:id`,
    mobileChat: `${ROUTE_PATHS.mobileInbox}/:id`,
    mobileInboxShare: `${ROUTE_PATHS.mobileInbox}/share`,
    mobileCustomerDetails: `${ROUTE_PATHS.mobileCustomers}/:id`,
    mobileVisitorDetails: '/m/visitor/:id',
};

export const ROUTE_PREFIXES = {
    orderDetails: `${ROUTE_PATHS.orders}/`,
    productDetails: '/inventory/product/',
    purchaseOrderDetails: '/inventory/purchase-orders/',
    customerDetails: `${ROUTE_PATHS.customers}/`,
    helpArticle: '/help/article/',
    invoiceDesignerById: `${ROUTE_PATHS.invoicesDesign}/`,
    mobileOrderDetails: `${ROUTE_PATHS.mobileOrders}/`,
    mobileChat: `${ROUTE_PATHS.mobileInbox}/`,
    mobileCustomerDetails: `${ROUTE_PATHS.mobileCustomers}/`,
    mobileVisitorDetails: '/m/visitor/',
    inboxDetail: `${ROUTE_PATHS.inbox}/`,
} as const;

export const EXACT_ROUTE_TITLES: Record<string, string> = {
    [ROUTE_PATHS.home]: 'Home',
    [ROUTE_PATHS.login]: 'Login',
    [ROUTE_PATHS.register]: 'Register',
    [ROUTE_PATHS.forgotPassword]: 'Forgot Password',
    [ROUTE_PATHS.resetPassword]: 'Reset Password',
    [ROUTE_PATHS.privacyPolicy]: 'Privacy Policy',
    [ROUTE_PATHS.dataDeletion]: 'Data Deletion',
    [ROUTE_PATHS.termsOfService]: 'Terms of Service',
    [ROUTE_PATHS.dashboard]: 'Dashboard',
    [ROUTE_PATHS.orders]: 'Orders',
    [ROUTE_PATHS.abandonedCarts]: 'Abandoned Carts',
    [ROUTE_PATHS.inventory]: 'Inventory',
    [ROUTE_PATHS.supplyChain]: 'Supply Chain',
    [ROUTE_PATHS.inventoryBomSync]: 'BOM Sync',
    [ROUTE_PATHS.inventoryForecasts]: 'Inventory Forecasts',
    [ROUTE_PATHS.customers]: 'Customers',
    [ROUTE_PATHS.customerSegments]: 'Customer Segments',
    [ROUTE_PATHS.marketing]: 'Marketing',
    [ROUTE_PATHS.ads]: 'Paid Ads',
    [ROUTE_PATHS.capiHealth]: 'CAPI Health',
    [ROUTE_PATHS.seo]: 'SEO',
    [ROUTE_PATHS.seoContent]: 'SEO Content',
    [ROUTE_PATHS.feeds]: 'Feeds',
    [ROUTE_PATHS.aiManager]: 'AI Manager',
    [ROUTE_PATHS.broadcasts]: 'Broadcasts',
    [ROUTE_PATHS.emails]: 'Email Dashboard',
    [ROUTE_PATHS.emailLists]: 'Email Lists',
    [ROUTE_PATHS.emailSettings]: 'Email Settings',
    [ROUTE_PATHS.emailLogs]: 'Email Logs',
    [ROUTE_PATHS.blockedContacts]: 'Blocked Contacts',
    [ROUTE_PATHS.flows]: 'Flows',
    [ROUTE_PATHS.inbox]: 'Inbox',
    [ROUTE_PATHS.live]: 'Live Analytics',
    [ROUTE_PATHS.analytics]: 'Analytics',
    [ROUTE_PATHS.analyticsRevenue]: 'Revenue Analytics',
    [ROUTE_PATHS.analyticsAttribution]: 'Attribution Analytics',
    [ROUTE_PATHS.analyticsClv]: 'CLV Analytics',
    [ROUTE_PATHS.reviews]: 'Reviews',
    [ROUTE_PATHS.help]: 'Help Center',
    [ROUTE_PATHS.reports]: 'Reports',
    [ROUTE_PATHS.reportsGoldPriceMargin]: 'Gold Price Margin Report',
    [ROUTE_PATHS.team]: 'Team',
    [ROUTE_PATHS.wizard]: 'Setup Wizard',
    [ROUTE_PATHS.settings]: 'Settings',
    [ROUTE_PATHS.profile]: 'Profile',
    [ROUTE_PATHS.invoicesDesign]: 'Invoice Designer',
    [ROUTE_PATHS.policies]: 'Policies',
    [ROUTE_PATHS.crawlers]: 'Crawler Shield',
    [ROUTE_PATHS.admin]: 'Admin Dashboard',
    [ROUTE_PATHS.adminAccounts]: 'Admin Accounts',
    [ROUTE_PATHS.adminLogs]: 'Admin Logs',
    [ROUTE_PATHS.adminBroadcast]: 'Admin Broadcast',
    [ROUTE_PATHS.adminCredentials]: 'Admin Credentials',
    [ROUTE_PATHS.adminAiPrompts]: 'Admin AI Prompts',
    [ROUTE_PATHS.adminSettings]: 'Admin Settings',
    [ROUTE_PATHS.adminDiagnostics]: 'Admin Diagnostics',
    [ROUTE_PATHS.adminBackups]: 'Admin Backups',
    [ROUTE_PATHS.mobileDashboard]: 'Mobile Dashboard',
    [ROUTE_PATHS.mobileOrders]: 'Mobile Orders',
    [ROUTE_PATHS.mobileInbox]: 'Mobile Inbox',
    [ROUTE_PATHS.mobileAnalytics]: 'Mobile Analytics',
    [ROUTE_PATHS.mobileInventory]: 'Mobile Inventory',
    [ROUTE_PATHS.mobileMore]: 'Mobile More',
    [ROUTE_PATHS.mobileProfile]: 'Mobile Profile',
    [ROUTE_PATHS.mobileSettings]: 'Mobile Settings',
    [ROUTE_PATHS.mobileCustomers]: 'Mobile Customers',
    [ROUTE_PATHS.mobileNotifications]: 'Mobile Notifications',
    [ROUTE_PATHS.mobileLiveVisitors]: 'Mobile Live Visitors',
};

const DYNAMIC_ROUTE_TITLES: Array<{ prefix: string; title: string }> = [
    { prefix: ROUTE_PREFIXES.orderDetails, title: 'Order Details' },
    { prefix: ROUTE_PREFIXES.productDetails, title: 'Product Details' },
    { prefix: ROUTE_PREFIXES.purchaseOrderDetails, title: 'Purchase Order' },
    { prefix: ROUTE_PREFIXES.customerDetails, title: 'Customer Details' },
    { prefix: ROUTE_PREFIXES.helpArticle, title: 'Help Article' },
    { prefix: ROUTE_PREFIXES.invoiceDesignerById, title: 'Invoice Designer' },
    { prefix: ROUTE_PREFIXES.mobileOrderDetails, title: 'Mobile Order Details' },
    { prefix: ROUTE_PREFIXES.mobileChat, title: 'Mobile Chat' },
    { prefix: ROUTE_PREFIXES.mobileCustomerDetails, title: 'Mobile Customer Details' },
    { prefix: ROUTE_PREFIXES.mobileVisitorDetails, title: 'Mobile Visitor Details' },
];

export function getRouteTitle(pathname: string): string {
    const exactTitle = EXACT_ROUTE_TITLES[pathname];
    if (exactTitle) return exactTitle;

    const dynamicTitle = DYNAMIC_ROUTE_TITLES.find((route) => pathname.startsWith(route.prefix));
    if (dynamicTitle) return dynamicTitle.title;

    return 'Dashboard';
}
