import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, ImageOff } from 'lucide-react';
import type { WholesaleBranding, WholesaleCatalog, WholesaleDefaults, WholesaleProductSummary } from '../../types/wholesaleCatalog';
import { buildCatalogPreview, type CatalogPreviewPage } from './catalogPreviewHelpers';

export function WholesaleCatalogPreview({ catalog, products, defaults, branding }: { catalog: WholesaleCatalog; products: WholesaleProductSummary[]; defaults: WholesaleDefaults; branding: WholesaleBranding }) {
    const preview = useMemo(() => buildCatalogPreview(catalog, products, defaults, branding), [branding, catalog, defaults, products]);
    const [pageIndex, setPageIndex] = useState(0);
    useEffect(() => setPageIndex(index => Math.min(index, preview.pages.length - 1)), [preview.pages.length]);
    const page = preview.pages[pageIndex];
    const accent = String(catalog.brandingOverrides.accentColor || branding.accentColor || branding.primaryColor || '#4f46e5');
    return <section className="space-y-3">
        <div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold text-slate-900 dark:text-white">Browser catalog preview</h3><p className="text-sm font-medium text-amber-700 dark:text-amber-300">Approximate preview — generated PDF is authoritative</p></div><div className="flex items-center gap-2 text-sm"><button aria-label="Previous preview page" disabled={pageIndex === 0} onClick={() => setPageIndex(index => index - 1)} className="rounded-lg border border-slate-300 p-2 disabled:opacity-30 dark:border-slate-600"><ChevronLeft size={16} /></button><span>Page {pageIndex + 1} of {preview.pages.length}</span><button aria-label="Next preview page" disabled={pageIndex === preview.pages.length - 1} onClick={() => setPageIndex(index => index + 1)} className="rounded-lg border border-slate-300 p-2 disabled:opacity-30 dark:border-slate-600"><ChevronRight size={16} /></button><button onClick={() => setPageIndex(preview.pages.length - 1)} className="rounded-lg px-2 py-2 font-medium text-indigo-600 hover:bg-indigo-50 dark:text-indigo-300">Terms page</button></div></div>
        <div className="aspect-[1.414/1] min-h-[360px] overflow-y-auto rounded-xl border border-slate-300 bg-[#fbfaf6] p-5 text-slate-900 shadow-inner dark:border-slate-600" style={{ fontFamily: branding.bodyFont || 'Arial, sans-serif' }}>
            <PreviewPage page={page} accent={accent} catalog={catalog} taxLabel={preview.pricesIncludeTax ? 'Prices include tax' : 'Prices exclude tax'} priceNotice={preview.priceNotice} />
        </div>
    </section>;
}

function PreviewPage({ page, accent, catalog, taxLabel, priceNotice }: { page: CatalogPreviewPage; accent: string; catalog: WholesaleCatalog; taxLabel: string; priceNotice: string | null }) {
    if (page.kind === 'cover') return <div className="flex min-h-[320px] flex-col justify-between rounded-lg border-8 p-8" style={{ borderColor: accent }}><div className="text-xs font-bold uppercase tracking-[0.3em]" style={{ color: accent }}>Wholesale collection</div><div><h4 className="max-w-2xl text-4xl font-black leading-tight">{page.title}</h4>{page.subtitle && <p className="mt-3 text-xl text-slate-600">{page.subtitle}</p>}<p className="mt-6 max-w-xl whitespace-pre-line text-sm text-slate-600">{page.coverText}</p></div><div className="text-sm font-semibold">Fast landscape approximation</div></div>;
    if (page.kind === 'terms') return <div><div className="mb-4 border-b-4 pb-2" style={{ borderColor: accent }}><h4 className="text-2xl font-black">Commercial terms</h4><p className="text-xs text-slate-500">Structured final-page approximation</p></div><div className="grid grid-cols-2 gap-x-6 gap-y-4">{page.sections.map((section, index) => <section key={`${section.heading}-${index}`}><h5 className="text-sm font-bold" style={{ color: accent }}>{section.heading}</h5><p className="mt-1 whitespace-pre-line text-xs leading-relaxed text-slate-700">{section.content}</p></section>)}</div>{Object.keys(page.paymentCallout).length > 0 && <RecordSummary title="Payment" value={page.paymentCallout} />}{Object.keys(page.footerDetails).length > 0 && <RecordSummary title="Business details" value={page.footerDetails} />}</div>;
    return <div><div className="mb-4 flex items-end justify-between border-b-4 pb-2" style={{ borderColor: accent }}><div><h4 className="text-2xl font-black">{page.category}</h4>{page.continued && <span className="text-xs font-bold uppercase tracking-widest text-slate-500">Continued</span>}</div><div className="text-right text-xs text-slate-500"><div>{taxLabel}</div>{priceNotice && <div>{priceNotice}</div>}</div></div><div className="grid grid-cols-4 gap-3">{page.products.map(product => <ProductCard key={product.id} product={product} accent={accent} />)}</div></div>;
}

function ProductCard({ product, accent }: { product: WholesaleProductSummary; accent: string }) {
    const tiers = product.profile?.priceTiers || [];
    return <article className="flex min-h-48 flex-col rounded-lg border border-slate-300 bg-white p-2 shadow-sm"><div className="aspect-[4/3] overflow-hidden rounded bg-slate-100">{product.imageUrl ? <img src={product.imageUrl} alt="" className="h-full w-full object-contain" /> : <div className="flex h-full items-center justify-center text-slate-400"><ImageOff size={24} /></div>}</div><h5 className="mt-2 line-clamp-2 text-sm font-bold">{product.name}</h5><div className="text-[10px] text-slate-500">{product.sku ? `SKU ${product.sku}` : 'No SKU'}{product.rrp ? ` · RRP $${product.rrp}` : ''}</div>{product.profile?.personalisationTypes.length ? <div className="mt-1 flex flex-wrap gap-1">{product.profile.personalisationTypes.map(process => <span key={process} className="rounded px-1 py-0.5 text-[9px] font-bold text-white" style={{ backgroundColor: accent }}>{process}</span>)}</div> : null}<div className="mt-2 text-[10px] leading-relaxed">{tiers.map(tier => <div key={tier.minimumQuantity}>{tier.minimumQuantity}+: {tier.isPoa ? 'POA' : `$${tier.unitPrice}`}</div>)}</div>{product.profile?.notesDocument && <p className="mt-auto line-clamp-2 pt-2 text-[9px] text-slate-500">{product.profile.notesDocument}</p>}</article>;
}

function RecordSummary({ title, value }: { title: string; value: Record<string, string | number | boolean | null | string[]> }) {
    return <section className="mt-5 border-t border-slate-300 pt-3"><h5 className="text-sm font-bold">{title}</h5><div className="mt-1 grid grid-cols-2 gap-1 text-xs text-slate-600">{Object.entries(value).map(([key, entry]) => <div key={key}><span className="font-semibold">{key.replace(/([A-Z])/g, ' $1')}:</span> {Array.isArray(entry) ? entry.join(', ') : String(entry ?? '')}</div>)}</div></section>;
}
