/**
 * ROI Stat Card - AI Co-Pilot Value Attribution Widget
 * 
 * Displays the value generated by AI Co-Pilot including
 * time savings, cost savings, and actions executed.
 * Part of AI Co-Pilot v2.
 */

import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useAccount } from '../../context/AccountContext';
import { Logger } from '../../utils/logger';
import {
    TrendingUp,
    Clock,
    DollarSign,
    Zap,
    ChevronRight,
    Loader2,
    ArrowUpRight
} from 'lucide-react';

// =============================================================================
// TYPES
// =============================================================================

interface ROIQuickStats {
    totalValue: number;
    actionsExecuted: number;
    hoursSaved: number;
    pendingActions: number;
}

interface ROIStatCardProps {
    onClick?: () => void;
    className?: string;
}

// =============================================================================
// COMPONENT
// =============================================================================

export function ROIStatCard({ onClick, className = '' }: ROIStatCardProps) {
    const { token } = useAuth();
    const { currentAccount } = useAccount();
    const [stats, setStats] = useState<ROIQuickStats | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState(false);

    const headers = useCallback(() => ({
        'Authorization': `Bearer ${token}`,
        'X-Account-ID': currentAccount?.id || '',
        'Content-Type': 'application/json'
    }), [token, currentAccount?.id]);

    useEffect(() => {
        if (!currentAccount) return;

        const fetchStats = async () => {
            try {
                const res = await fetch('/api/ads/roi/quick-stats', { headers: headers() });
                if (res.ok) {
                    const data = await res.json();
                    setStats(data.data);
                } else {
                    setError(true);
                }
            } catch (err) {
                Logger.error('Failed to fetch ROI stats', { error: err });
                setError(true);
            } finally {
                setIsLoading(false);
            }
        };

        fetchStats();

        // Refetch every 5 minutes
        const interval = setInterval(fetchStats, 5 * 60 * 1000);
        return () => clearInterval(interval);
    }, [currentAccount, headers]);

    if (isLoading) {
        return (
            <div className={`bg-gradient-to-br from-violet-900/50 to-purple-900/50 rounded-2xl border border-violet-500/20 p-6 ${className}`}>
                <div className="flex items-center justify-center h-24">
                    <Loader2 className="w-6 h-6 text-violet-400 animate-spin" />
                </div>
            </div>
        );
    }

    if (error || !stats) {
        return null; // Silent fail for widget
    }

    const formatCurrency = (value: number) => {
        if (value >= 1000) {
            return `$${(value / 1000).toFixed(1)}k`;
        }
        return `$${value.toFixed(0)}`;
    };

    return (
        <div
            onClick={onClick}
            className={`
                bg-gradient-to-br from-violet-900/50 to-purple-900/50 
                rounded-2xl border border-violet-500/20 
                p-6 cursor-pointer
                hover:border-violet-500/40 hover:shadow-lg hover:shadow-violet-500/10
                transition-all duration-300
                ${className}
            `}
        >
            {/* Header */}
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                    <div className="p-2 bg-violet-500/20 rounded-lg">
                        <Zap className="w-5 h-5 text-violet-400" />
                    </div>
                    <span className="text-sm font-medium text-gray-300">
                        AI Co-Pilot Value
                    </span>
                </div>
                <div className="flex items-center gap-1 text-xs text-violet-400">
                    <span>Last 30 days</span>
                    <ChevronRight className="w-4 h-4" />
                </div>
            </div>

            {/* Main Value */}
            <div className="mb-4">
                <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-bold text-white">
                        {formatCurrency(stats.totalValue)}
                    </span>
                    <span className="text-sm text-green-400 flex items-center gap-0.5">
                        <ArrowUpRight className="w-4 h-4" />
                        value generated
                    </span>
                </div>
            </div>

            {/* Stats Grid */}
            <div className="grid grid-cols-3 gap-4">
                <div className="text-center">
                    <div className="flex items-center justify-center gap-1 text-2xl font-semibold text-white">
                        <Clock className="w-4 h-4 text-blue-400" />
                        {stats.hoursSaved}h
                    </div>
                    <div className="text-xs text-gray-500 mt-1">Time Saved</div>
                </div>

                <div className="text-center">
                    <div className="flex items-center justify-center gap-1 text-2xl font-semibold text-white">
                        <TrendingUp className="w-4 h-4 text-green-400" />
                        {stats.actionsExecuted}
                    </div>
                    <div className="text-xs text-gray-500 mt-1">Actions</div>
                </div>

                <div className="text-center">
                    <div className="flex items-center justify-center gap-1 text-2xl font-semibold text-white">
                        <DollarSign className="w-4 h-4 text-amber-400" />
                        {stats.pendingActions}
                    </div>
                    <div className="text-xs text-gray-500 mt-1">Pending</div>
                </div>
            </div>

            {/* Pending Actions CTA */}
            {stats.pendingActions > 0 && (
                <div className="mt-4 pt-4 border-t border-violet-500/20">
                    <div className="flex items-center justify-between text-sm">
                        <span className="text-amber-400">
                            {stats.pendingActions} actions awaiting review
                        </span>
                        <span className="text-violet-400">Review →</span>
                    </div>
                </div>
            )}
        </div>
    );
}

export default ROIStatCard;
