-- AlterTable
ALTER TABLE "WooProduct" 
ADD COLUMN IF NOT EXISTS "images" JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "weight" DECIMAL(10,4),
ADD COLUMN IF NOT EXISTS "length" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "width" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "height" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "isGoldPriceApplied" BOOLEAN NOT NULL DEFAULT false;
